name: Update FRED Data

on:
  schedule:
    - cron: "0 0 */14 * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # fetch the entire commit history
          ref: main        # explicitly checkout main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install node-fetch@2 papaparse

      - name: Run update script
        run: node update-fred-data.js

      - name: Force Push Changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git

          # Stage changes
          git add fredData.json
          # Commit
          git commit -m "Update FRED data" || echo "No changes to commit"
          # Force push
          git push origin HEAD:main --force
