name: Update FRED Data

on:
  schedule:
    - cron: "0 0 */14 * *"  # runs every 14 days
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    # fetch full commit history
          ref: main         # explicitly checkout main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create minimal package.json if not present
        run: |
          if [ ! -f package.json ]; then
            echo '{"name": "egg-dashboard", "version": "1.0.0", "dependencies": {}}' > package.json;
          fi

      - name: Install dependencies
        run: npm install node-fetch@2 papaparse adm-zip

      - name: List installed modules (debug)
        run: ls -la node_modules

      - name: Hard Reset to Remote Main
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git
          git fetch origin main
          git reset --hard origin/main

      - name: Run update script
        run: node update-fred-data.js

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git add fredData.json
          git commit -m "Update FRED data" || echo "No changes to commit"
          git push origin HEAD:main --force