name: Update FRED Data

on:
  schedule:
    - cron: "0 0 */14 * *"  # runs every 14 days
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # fetch the entire commit history
          ref: main        # explicitly checkout main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install node-fetch@2 papaparse adm-zip

      - name: Hard Reset to Remote Main
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git
          # Fetch all remote commits
          git fetch origin main
          # Discard local commits and match remote
          git reset --hard origin/main

      - name: Run update script
        run: node update-fred-data.js

      - name: Force push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          # Stage the newly updated file
          git add fredData.json
          # Commit changes
          git commit -m "Update FRED data" || echo "No changes to commit"
          # Force push to overwrite remote main
          git push origin HEAD:main --force
